; For when you really need to get your point across, but don't want results coming up with a search

::arse::ärsë
::arsehole::ärsëhólë
::ass::äss
::balls::bälls
::bastard::bästärd
::bitch::bîtch
::bukkake::būkkäkë
::bullshit::būllshît
::clunge::clūngë
::cock::cóck
::cocksucker::cócksūckër
::crap::cräp
::cunt::cūnt
::damn::dämn
::dick::dîck
::dickhead::dîckhëäd
::dildo::dîldó
::fag::notCool
::faggot::seriouslyNotCool
::fuck::fūck
::goddam::góddäm
::ho::hó
::jesus christ::jësūs chrîst
::jizz::jîzz
::minge::mîngë
::motherfucker::móthërfūckër
::munter::mūntër
::pissed::pîssëd
::pussy::pūssy
::shit::shît
::skank::skänk
::slag::släg
::slapper::släppër
::slut::slūt
::tits::tîts
::wanker::wänkër
::whore::whórë
